### ISSUE TITLE
Problem with reissue

### ISSUE THREAD

**Issue by erikbor** [riboseinc/digicert-cli#46]
```
$ digicert order reissue 2373341 --crt wildcard.domain.com.csr --output ./
/Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-0.1.2/lib/digicert/request.rb:59:in `raise_response_error': A request to Digicert API failed: (Digicert::Errors::RequestError)
[{"code":"required_param:certificate.server_platform","message":"certificate.server_platform is a required parameter."},{"code":"required_param:certificate.signature_hash","message":"certificate.signature_hash is a required parameter."}]
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-0.1.2/lib/digicert/request.rb:19:in `run'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-0.1.2/lib/digicert/request.rb:23:in `parse'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-0.1.2/lib/digicert/actions/create.rb:11:in `create'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-0.1.2/lib/digicert/order_manager.rb:8:in `create'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-cli-0.2.0/lib/digicert/cli/order_reissuer.rb:27:in `reissue_an_order'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-cli-0.2.0/lib/digicert/cli/order_reissuer.rb:10:in `create'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-cli-0.2.0/lib/digicert/cli/commands/order.rb:40:in `reissue_an_order'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-cli-0.2.0/lib/digicert/cli/commands/order.rb:28:in `reissue'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-cli-0.2.0/lib/digicert/cli.rb:35:in `start'
	from /Users/test/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/digicert-cli-0.2.0/bin/digicert:21:in `<top (required)>'
	from /Users/test/.rbenv/versions/2.3.4/bin/digicert:22:in `load'
	from /Users/test/.rbenv/versions/2.3.4/bin/digicert:22:in `<main>'
```

**Comment by abunashir** [comment]
Thanks @erikbor! I will debug this one in more details and will fix the issue soon.

**Comment by abunashir** [comment]
@erikbor: After debugging this, it looks like this issue is from the `DigiCert` gem, whenever we are passing some custom attributes then it's overriding the existing attributes, which is not the way it supposed to work, I will add the fix in the DigiCert gem and then will update the interface here, Thanks for reporting this issue.

cc: @ronaldtse

**Comment by erikbor** [comment]
Awesome! Thanks @abunashir

**Comment by abunashir** [comment]
@erikbor: Sorry for the long delay, but just merged this fixes.

**Comment by erikbor** [comment]
@abunashir thanks!
