### ISSUE TITLE
Unable to show certificate duplicates 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/digicert-cli#65]
Can't seem to list certificate duplicates. @abunashir could you please help fix this? Thanks!

```sh
$ digicert certificate duplicates 10101010 # this is a real order ID
Traceback (most recent call last):
	17: from /Users/me/.rbenv/versions/2.5.1/bin/digicert:23:in `<main>'
	16: from /Users/me/.rbenv/versions/2.5.1/bin/digicert:23:in `load'
	15: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/digicert-cli-0.5.0/bin/digicert:21:in `<top (required)>'
	14: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/digicert-cli-0.5.0/lib/digicert/cli.rb:35:in `start'
	13: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/digicert-cli-0.5.0/lib/digicert/cli/util.rb:27:in `run'
	12: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	11: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	10: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	 8: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:242:in `block in subcommand'
	 7: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	 6: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	 5: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	 4: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	 3: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/digicert-cli-0.5.0/lib/digicert/cli/commands/certificate.rb:36:in `duplicates'
	 2: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/digicert-cli-0.5.0/lib/digicert/cli/certificate.rb:10:in `duplicates'
	 1: from /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/digicert-cli-0.5.0/lib/digicert/cli/certificate.rb:67:in `display_in_table'
/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/digicert-cli-0.5.0/lib/digicert/cli/util.rb:7:in `make_it_pretty': unknown keyword: table_wdith (ArgumentError)
```

**Comment by abunashir** [comment]
@ronaldtse: Seems like, this was an issue with our `Digicert::Util` class, we were passing an invalid argument, but duplicate should be as functional as before. I don't have access to that order, so I can't test but could you please double check with the pull request branch?

**Comment by abunashir** [comment]
Update: I just merged and pushed it to ruby gems, so please test with the latest version from rubygems. Version:  `0.5.1`.

**Comment by ronaldtse** [comment]
Thanks @abunashir !

**Comment by abunashir** [comment]
@ronaldtse: Are we good with this one? or is this still an issue?
