### ISSUE TITLE
Can't fetch the certificates of an order

### ISSUE THREAD

**Issue by tkapoulas** [riboseinc/digicert-cli#67]
```
$ digicert certificate fetch 6067927 --output ./ --debug
...
================[API Reqeust End]=================
/var/lib/gems/2.3.0/gems/digicert-cli-0.5.1/lib/digicert/cli/certificate.rb:44:in 'download_certificate': uninitialized constant Digicert::CLI::CertificateDownloader (NameError)
Did you mean?  Digicert::CertificateDownloader
	from /var/lib/gems/2.3.0/gems/digicert-cli-0.5.1/lib/digicert/cli/certificate.rb:39:in 'apply_option_flags'
	from /var/lib/gems/2.3.0/gems/digicert-cli-0.5.1/lib/digicert/cli/certificate.rb:5:in 'fetch'
	from /var/lib/gems/2.3.0/gems/digicert-cli-0.5.1/lib/digicert/cli/commands/certificate.rb:14:in 'fetch'
	from /var/lib/gems/2.3.0/gems/thor-1.0.1/lib/thor/command.rb:27:in 'run'
	from /var/lib/gems/2.3.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in 'invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-1.0.1/lib/thor.rb:392:in 'dispatch'
	from /var/lib/gems/2.3.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in 'invoke'
	from /var/lib/gems/2.3.0/gems/thor-1.0.1/lib/thor.rb:243:in 'block in subcommand'
	from /var/lib/gems/2.3.0/gems/thor-1.0.1/lib/thor/command.rb:27:in 'run'
	from /var/lib/gems/2.3.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in 'invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-1.0.1/lib/thor.rb:392:in 'dispatch'
	from /var/lib/gems/2.3.0/gems/thor-1.0.1/lib/thor/base.rb:485:in 'start'
	from /var/lib/gems/2.3.0/gems/digicert-cli-0.5.1/lib/digicert/cli/util.rb:23:in 'run'
	from /var/lib/gems/2.3.0/gems/digicert-cli-0.5.1/lib/digicert/cli.rb:35:in 'start'
	from /var/lib/gems/2.3.0/gems/digicert-cli-0.5.1/bin/digicert:21:in '<top (required)>'
	from /usr/local/bin/digicert:22:in 'load'
	from /usr/local/bin/digicert:22:in '<main>'
```

**Comment by ronaldtse** [comment]
@tkapoulas sorry about this -- @abunashir could you help check? Thanks!

**Comment by abunashir** [comment]
Thanks for reporting this issue Thomas, this should be fixed in our next release.
